---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - .ember
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install
  - node/build.js --cache

script:
  - npm test
