---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

services: mongodb

before_install:
  - npm config set spin false

install:
  #- npm install -g bower
  - npm install -g mocha
  - npm install
  #- npm run-script build

script:
  - npm test
